language: go

go:
    - 1.12.x

sudo: required

services:
    - docker

install:
    - go get -u -d github.com/magefile/mage
    - cd $GOPATH/src/github.com/magefile/mage
    - go run bootstrap.go
    - cd $TRAVIS_BUILD_DIR

before_script:
    - docker pull amarantin/hello-go:latest || true

script: mage -v buildDockerContainer

after_script:
    - docker images

before_deploy:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
    - provider: script
      skip_cleanup: true
      script: mage -v deployLatest
      on:
          branch: master
    - provider: script
      skip_cleanup: true
      script: mage -v deployVersion
      on:
          tags: true

notifications:  
    email:  
        on_success: always  
        on_failure: always
