language: go

go:
  - 1.12.x

sudo: required

services:
  - docker

script:
  - docker build --tag amarantin/hello-go .
  - docker run amarantin/hello-go

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push amarantin/hello-go
  on:
    branch: master
