language: go

go:
    - 1.12.x

sudo: required

services:
    - docker

before_script:
    - docker pull amarantin/hello-go:latest || true

script:
    - docker build --pull --cache-from amarantin/hello-go:latest --tag amarantin/hello-go .
    - docker run amarantin/hello-go

after_script:
    - docker images

before_deploy:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
    - export SEMVER=`git describe --abbrev=0 --tags`
    - echo "helllo sckript"
    - echo $SEMVER

deploy:
    #    - provider: script
    #      skip_cleanup: true
    #      script:
    #        - docker push amarantin/hello-go
    #      on:
    #        branch: master
    - provider: script
      skip_cleanup: true
      script:
        - echo $SEMVER
        - docker push amarantin/hello-go
      on:
        #tags: true
        branch: master



