language: go

go:
    - 1.12.x

sudo: required

services:
    - docker

before_script:
    - docker pull amarantin/hello-go:latest || true

script:
    - docker build --pull --cache-from amarantin/hello-go:latest --tag amarantin/hello-go .
    - docker run amarantin/hello-go

after_script:
    - docker images

before_deploy:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
    - provider: script
        script:
            - docker push amarantin/hello-go
        on:
            branch: master
    - provider: script
        script:
            - SEMVER=`git describe --abbrev=0 --tags` 
            - docker tag amarantin/hello-go:latest amarantin/hello-go:$SEMVER
            - docker push amarantin/hello-go:$SEMVER 
            - docker push amarantin/hello-go:latest
        on:
            tags: true



